"""empty message

Revision ID: 7d22651cbe87
Revises: 
Create Date: 2023-04-02 18:07:28.730199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d22651cbe87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('language', sa.Enum('english', 'russian', name='language'), server_default='english', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('pills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.Enum('pieces', 'mg', 'ml', name='unit'), nullable=True),
    sa.Column('dosage', sa.Integer(), nullable=True),
    sa.Column('intake', sa.Enum('before', 'during', 'after', name='intake'), nullable=True),
    sa.Column('startdate', sa.Date(), nullable=False),
    sa.Column('enddate', sa.Date(), nullable=False),
    sa.Column('days', sa.ARRAY(sa.SmallInteger()), nullable=True),
    sa.Column('times', sa.ARRAY(sa.Time()), nullable=False),
    sa.ForeignKeyConstraint(['author'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pills')
    op.drop_table('users')
    # ### end Alembic commands ###
    # TODO Remove enums
